### ISSUE TITLE
Your project has been added to a list of copyfree works.

### ISSUE THREAD

**Issue by apotheon** [dupliqr/dupliqr.github.io#4]
http://copyfree.org/resources/works#Dupli-QR

Please let me know if there are any inaccuracies to be corrected or
improvements to be made in the listing.

**Comment by kipbits** [comment]
i don't think this is completely accurate, since the project relies in part on code under Apache 2.0 license. The only parts that can be considered copyfree are my index.html & main.js plus the contents of folder KazuhikoArase. Lazar Laszlo clearly specified the Apache 2.0 license for his work. I therefore think you should have this in a list of partly-copyfree works. 

Thanks!

...and sorry for the confusion, i do plan to clarify this more in my repo soon. I have been afk this past week.

**Comment by apotheon** [comment]
Thank you.  I added information about license contamination to the entry.

**Comment by kipbits** [comment]
cool
